/**
 * Curriculum progressif — 7 niveaux, ~60 concepts numérotés.
 * L'ordre dans chaque niveau respecte les prérequis : aucun concept ne suppose
 * de connaissance d'un concept ultérieur.
 *
 * Chaque concept porte sa question anglaise pré-rédigée envoyée au backend.
 */

export type Concept = {
  /** Libellé court en français (ex: "Décorateurs") */
  fr: string;
  /** Objectif d'apprentissage (sous-titre court) */
  obj: string;
  /** Question anglaise envoyée au backend RAG */
  en: string;
};

export type Corpus =
  | "python"
  | "fastapi"
  | "pydantic"
  | "nextjs"
  | "typescript"
  | "tailwind"
  | "self"
  // Phase 7 — écosystème
  | "pytest"
  | "httpx"
  | "sqlalchemy"
  | "zod"
  | "tanstack_query"
  | "vitest"
  // Phase 12 — front-end MDN
  | "html"
  | "css"
  | "javascript";

export type Level = {
  /** Identifiant du niveau (ex: "1", "FA1") — sert aussi de clé visuelle */
  num: string;
  /** Titre court */
  title: string;
  /** Objectif d'apprentissage du niveau */
  goal: string;
  /** Icône Material Symbols pour la sidebar */
  icon: string;
  /** Corpus dont relève ce niveau (sert au regroupement et au filtrage) */
  corpus: Corpus;
  concepts: Concept[];
};

export const CURRICULUM: Level[] = [
  {
    num: "1",
    title: "Premiers pas",
    goal: "Comprendre comment Python stocke et manipule les données simples.",
    icon: "terminal",
    corpus: "python",
    concepts: [
      { fr: "Variables et types simples", obj: "int, float, str, bool, None — la base de tout",
        en: "What are the basic data types in Python (int, float, str, bool, None) and how does variable assignment work? Give simple examples." },
      { fr: "Opérateurs", obj: "Arithmétiques, comparaison, logiques",
        en: "What are the arithmetic, comparison, and logical operators in Python? Show their precedence and examples." },
      { fr: "Chaînes de caractères", obj: "Concaténation, indexation, slicing, méthodes",
        en: "How do strings work in Python? Show indexing, slicing, and common methods like upper, lower, strip, split, replace, find." },
      { fr: "f-strings (introduction)", obj: "Insérer des variables dans du texte",
        en: "How do f-strings work in Python for basic string formatting? Show variable insertion and simple expressions inside braces." },
      { fr: "Entrée / sortie", obj: "print() et input() pour interagir",
        en: "How do print() and input() work in Python? Show keyword arguments of print (sep, end, file) and reading user input." },
      { fr: "Conditions if / elif / else", obj: "Faire des choix",
        en: "How do if, elif, and else conditions work in Python? Show truthy/falsy values and nested conditions with examples." },
      { fr: "Boucles while", obj: "Répéter tant qu'une condition tient",
        en: "How does the while loop work in Python? Show break, continue, and the else clause with examples." },
      { fr: "Boucles for et range()", obj: "Itérer sur une séquence",
        en: "How does the for loop work in Python with range() and enumerate()? Show examples with break, continue, and else." },
      { fr: "Listes", obj: "Collection ordonnée et modifiable",
        en: "How do lists work in Python? Show creation, indexing, slicing, and methods: append, extend, insert, pop, remove, sort, reverse." },
      { fr: "Tuples", obj: "Collection ordonnée immuable",
        en: "What are tuples in Python and when should I use them instead of lists? Show packing, unpacking, and named tuples." },
      { fr: "Dictionnaires", obj: "Paires clé-valeur",
        en: "How do dictionaries work in Python? Show creation, access, iteration, and methods: keys, values, items, get, update, pop." },
      { fr: "Ensembles (sets)", obj: "Collection sans doublons",
        en: "What are sets in Python? Show creation, the operations union, intersection, difference, symmetric_difference, and frozen sets." },
    ],
  },
  {
    num: "2",
    title: "Structurer son code",
    goal: "Organiser ton code en fonctions, modules, et gérer les erreurs.",
    icon: "rebase_edit",
    corpus: "python",
    concepts: [
      { fr: "Définir une fonction", obj: "def, paramètres, return",
        en: "How do I define and call functions in Python? Show parameters, return values, and docstrings with examples." },
      { fr: "Paramètres par défaut", obj: "Valeurs par défaut et arguments nommés",
        en: "How do default parameter values and keyword arguments work in Python functions? Show the mutable default argument trap." },
      { fr: "*args et **kwargs", obj: "Nombre variable d'arguments",
        en: "What are *args and **kwargs in Python function definitions? Show packing/unpacking and forwarding arguments." },
      { fr: "Portée des variables", obj: "local, global, nonlocal",
        en: "How does variable scope work in Python? Explain LEGB rule, global and nonlocal keywords with examples." },
      { fr: "Fonctions lambda", obj: "Petites fonctions anonymes",
        en: "What are lambda functions in Python and when should I use them? Show usage with sorted, map, filter." },
      { fr: "Modules et imports", obj: "Organiser le code en fichiers",
        en: "How do Python modules and imports work? Explain import, from/import, as, __name__, __main__, and the import system." },
      { fr: "Gestion d'erreurs", obj: "try / except / finally / raise",
        en: "How do try, except, finally, else, and raise work in Python? Show common exception types and creating custom exceptions." },
      { fr: "Lire et écrire des fichiers", obj: "open(), read, write, modes",
        en: "How do I read and write files in Python with open()? Show modes (r, w, a, b), text vs binary, and best practices." },
      { fr: "Context managers (with)", obj: "Gérer des ressources proprement",
        en: "How do context managers and the with statement work in Python? Show file handling and writing custom context managers with __enter__/__exit__ and contextlib." },
    ],
  },
  {
    num: "3",
    title: "Style pythonique",
    goal: "Écrire du code Python idiomatique, concis et expressif.",
    icon: "auto_awesome",
    corpus: "python",
    concepts: [
      { fr: "Compréhensions de listes", obj: "[x*2 for x in items if x > 0]",
        en: "What are list comprehensions in Python? Show simple, conditional, and nested examples vs equivalent for loops." },
      { fr: "Compréhensions dict et set", obj: "Variantes pour dict et set",
        en: "How do dictionary and set comprehensions work in Python? Show practical examples with conditions." },
      { fr: "Le protocole d'itération", obj: "__iter__ et __next__",
        en: "What is the iterator protocol in Python? Show __iter__, __next__, StopIteration, and writing a custom iterator class." },
      { fr: "Générateurs et yield", obj: "Produire des valeurs paresseusement",
        en: "What are generators and the yield keyword in Python? Show generator functions, generator expressions, and yield from." },
      { fr: "Closures", obj: "Fonctions qui capturent leur contexte",
        en: "What are closures in Python? Show how inner functions capture variables from enclosing scopes with examples." },
      { fr: "Décorateurs (introduction)", obj: "Modifier une fonction avec @",
        en: "How do Python decorators work? Show the @decorator syntax with a simple example like a logger or timer." },
      { fr: "Décorateurs avec arguments", obj: "@decorator(param) — niveau supplémentaire",
        en: "How do I write decorators that accept arguments in Python? Show the three-level function pattern with examples." },
      { fr: "map, filter, reduce", obj: "Style fonctionnel",
        en: "How do map, filter, and reduce work in Python? Show examples and compare with list comprehensions." },
      { fr: "f-strings avancés", obj: "Format spec : alignement, padding, précision",
        en: "How do f-strings work with advanced formatting in Python? Show alignment, width, padding, number precision, !r/!s/!a, and = for debugging." },
    ],
  },
  {
    num: "4",
    title: "Programmation orientée objet",
    goal: "Modéliser ton domaine avec des classes et l'héritage.",
    icon: "architecture",
    corpus: "python",
    concepts: [
      { fr: "Classes et instances", obj: "class, self, créer un objet",
        en: "How do classes work in Python? Show class definition, instance creation, and the role of self." },
      { fr: "__init__ et attributs", obj: "Initialiser un objet",
        en: "How does __init__ work in Python classes? Show instance attributes vs class attributes with examples." },
      { fr: "Méthodes de classe et statiques", obj: "@classmethod et @staticmethod",
        en: "What is the difference between instance methods, @classmethod, and @staticmethod in Python? Show when to use each." },
      { fr: "__str__ et __repr__", obj: "Représentation textuelle d'un objet",
        en: "What are __str__ and __repr__ in Python? Show the difference, when each is called, and best practices." },
      { fr: "__eq__, __hash__, __lt__", obj: "Comparer des objets",
        en: "How do __eq__, __hash__, __lt__, __le__, __gt__, __ge__ work in Python? Show how to make objects comparable and hashable." },
      { fr: "__len__, __getitem__, __iter__", obj: "Faire un objet container",
        en: "How do __len__, __getitem__, __setitem__, __contains__, and __iter__ work in Python? Show building a custom container class." },
      { fr: "Héritage simple", obj: "class B(A) et super()",
        en: "How does class inheritance work in Python? Show single inheritance, super(), method overriding with examples." },
      { fr: "Héritage multiple et MRO", obj: "Plusieurs parents et l'ordre de résolution",
        en: "How does multiple inheritance work in Python? Explain the MRO (Method Resolution Order), the C3 linearization, and the diamond problem." },
      { fr: "@property", obj: "Attributs calculés, getters/setters",
        en: "How does @property work in Python? Show getters, setters, deleters, and how it replaces explicit accessors." },
      { fr: "Classes abstraites (ABC)", obj: "Forcer une interface dans les sous-classes",
        en: "How do abstract base classes work in Python with the abc module? Show ABC, abstractmethod, and ABCMeta." },
      { fr: "Dataclasses", obj: "Générer __init__, __repr__, __eq__ automatiquement",
        en: "How do dataclasses work in Python and what does the @dataclass decorator provide? Show frozen, default values, field(), and post_init." },
    ],
  },
  {
    num: "5",
    title: "Types et patterns modernes",
    goal: "Adopter les fonctionnalités récentes de Python (3.10+).",
    icon: "psychology",
    corpus: "python",
    concepts: [
      { fr: "Type hints basiques", obj: "Annoter paramètres et retours",
        en: "How do basic type hints work in Python? Show annotating function parameters, return types, and variables with simple types." },
      { fr: "typing : Optional, Union, List...", obj: "Types composés et génériques",
        en: "How does the typing module work in Python? Show Optional, Union, List, Dict, Tuple, Callable, TypeVar, and Generic." },
      { fr: "Type unions modernes (X | Y)", obj: "Syntaxe Python 3.10+",
        en: "How does the X | Y union syntax work for type hints in Python 3.10+? Compare with typing.Union and Optional." },
      { fr: "TypedDict et Protocol", obj: "Typer les dicts et le duck-typing",
        en: "What are TypedDict and Protocol in Python typing? Show structural subtyping examples and use cases." },
      { fr: "Pattern matching (match/case)", obj: "Filtrer par structure (3.10+)",
        en: "How does the match/case statement work in Python 3.10+? Show literal, capture, class, sequence, mapping, and guard patterns." },
      { fr: "Walrus operator (:=)", obj: "Assigner dans une expression",
        en: "What is the walrus operator (:=) in Python? Show use cases in while loops, list comprehensions, and conditions." },
      { fr: "Métaclasses", obj: "Classes qui créent des classes",
        en: "What are metaclasses in Python and how do they work? Show type() as a metaclass, the metaclass= argument, and __init_subclass__." },
    ],
  },
  {
    num: "6",
    title: "Concurrence et I/O",
    goal: "Faire plusieurs choses en parallèle, gérer l'asynchrone.",
    icon: "alt_route",
    corpus: "python",
    concepts: [
      { fr: "Threading et le GIL", obj: "Plusieurs threads, le verrou global",
        en: "How does threading work in Python? Show Thread, Lock, RLock, and explain the GIL and its implications for CPU vs I/O bound tasks." },
      { fr: "Multiprocessing", obj: "Vrai parallélisme, contourner le GIL",
        en: "How does multiprocessing work in Python? Show Process, Pool, Queue, and inter-process communication." },
      { fr: "async / await (introduction)", obj: "Coroutines et asyncio.run",
        en: "How do async/await and the basics of asyncio work in Python? Show defining coroutines, awaiting them, and running with asyncio.run." },
      { fr: "asyncio avancé", obj: "Tasks, gather, timeouts",
        en: "How does asyncio handle concurrent operations in Python? Show Tasks, asyncio.gather, semaphores, timeouts, and TaskGroup (3.11+)." },
      { fr: "subprocess", obj: "Lancer d'autres programmes",
        en: "How does the subprocess module work in Python? Show subprocess.run, capturing stdout/stderr, Popen, and shell vs list arguments." },
    ],
  },
  {
    num: "7",
    title: "Bibliothèque standard essentielle",
    goal: "Maîtriser les modules incontournables — « batteries included ».",
    icon: "library_books",
    corpus: "python",
    concepts: [
      { fr: "collections", obj: "Counter, defaultdict, deque, namedtuple",
        en: "What does the collections module provide in Python? Show Counter, defaultdict, deque, namedtuple, OrderedDict with examples." },
      { fr: "itertools", obj: "Outils d'itération efficaces",
        en: "What does the itertools module provide in Python? Show chain, cycle, count, combinations, permutations, groupby, product, accumulate, takewhile." },
      { fr: "functools", obj: "Outils pour fonctions",
        en: "What does functools provide in Python? Show partial, reduce, lru_cache, cache, wraps, singledispatch, total_ordering." },
      { fr: "pathlib", obj: "Manipulation moderne des chemins",
        en: "How does pathlib work in Python for file path manipulation? Show Path operations, read_text, write_text, glob, joinpath, and comparisons with os.path." },
      { fr: "json", obj: "Lire et écrire du JSON",
        en: "How do I read and write JSON in Python with the json module? Show dumps, loads, dump, load, custom encoders/decoders." },
      { fr: "csv", obj: "Lire et écrire du CSV",
        en: "How do I read and write CSV files in Python with the csv module? Show reader, writer, DictReader, DictWriter, dialects." },
      { fr: "re (regex)", obj: "Expressions régulières",
        en: "How does the re module work in Python for regular expressions? Show match, search, findall, finditer, sub, groups, named groups, and common flags." },
      { fr: "datetime", obj: "Dates, heures, durées",
        en: "How does the datetime module work in Python? Show datetime, date, time, timedelta, strftime, strptime, and timezones with zoneinfo." },
      { fr: "argparse", obj: "Arguments de ligne de commande",
        en: "How do I parse command-line arguments with argparse in Python? Show positional arguments, optional arguments, flags, subcommands, and type conversion." },
      { fr: "logging", obj: "Tracer ce que fait ton programme",
        en: "How does the logging module work in Python? Show levels, basicConfig, handlers, formatters, named loggers, and best practices vs print." },
      { fr: "unittest", obj: "Tester ton code",
        en: "How do I write unit tests with the unittest module in Python? Show TestCase, assertions, setUp, tearDown, test discovery, and mocks." },
      { fr: "os et sys", obj: "Système d'exploitation et interpréteur",
        en: "What do os and sys provide in Python? Show common operations on environment, paths, processes, arguments, and the interpreter." },
    ],
  },

  // ==========================================================================
  // FastAPI — backend API moderne, async-first
  // ==========================================================================
  {
    num: "FA1",
    title: "FastAPI · Fondations",
    goal: "Créer ta première API : routes, paramètres, méthodes HTTP.",
    icon: "bolt",
    corpus: "fastapi",
    concepts: [
      { fr: "Première application FastAPI", obj: "Hello world + uvicorn",
        en: "How do I create my first FastAPI application? Show app instantiation, first GET route, and how to run it with uvicorn." },
      { fr: "Path operations (méthodes HTTP)", obj: "GET, POST, PUT, DELETE, PATCH",
        en: "How do FastAPI path operation decorators work? Show @app.get, @app.post, @app.put, @app.delete, @app.patch with examples." },
      { fr: "Paramètres de chemin", obj: "/items/{item_id} + typage",
        en: "How do path parameters work in FastAPI? Show typed path parameters, enum path parameters, and path parameter ordering." },
      { fr: "Paramètres de requête", obj: "Query string + valeurs par défaut",
        en: "How do query parameters work in FastAPI? Show optional query parameters, default values, type conversion, and Query() metadata." },
      { fr: "Corps de requête", obj: "Body via Pydantic model",
        en: "How do I receive a request body in FastAPI? Show declaring a Pydantic model as parameter, automatic validation, and JSON parsing." },
      { fr: "Status codes & headers", obj: "Réponses HTTP propres",
        en: "How do I set status codes and response headers in FastAPI? Show status_code parameter, Response object, and custom headers." },
      { fr: "Cookies et headers reçus", obj: "Cookie() et Header()",
        en: "How do I read cookies and headers from incoming requests in FastAPI? Show Cookie() and Header() parameter declarations." },
      { fr: "Forms et uploads de fichiers", obj: "Form() et UploadFile",
        en: "How do I handle form data and file uploads in FastAPI? Show Form() parameters, UploadFile, and multiple file uploads." },
    ],
  },
  {
    num: "FA2",
    title: "FastAPI · Validation & modèles",
    goal: "Maîtriser la validation Pydantic dans FastAPI.",
    icon: "fact_check",
    corpus: "fastapi",
    concepts: [
      { fr: "Modèles Pydantic en entrée", obj: "BaseModel pour le body",
        en: "How do I declare request body models in FastAPI using Pydantic? Show BaseModel fields, optional fields, and nested models." },
      { fr: "Response models", obj: "response_model pour filtrer la sortie",
        en: "How does response_model work in FastAPI? Show filtering output fields, response_model_exclude_unset, and response_model_by_alias." },
      { fr: "Validation des champs", obj: "Field() + contraintes",
        en: "How do I add validation constraints to FastAPI request bodies with Pydantic Field()? Show min_length, max_length, ge, le, regex, examples." },
      { fr: "Plusieurs corps + paramètres", obj: "Body() pour mixer",
        en: "How do I declare multiple body parameters in a single FastAPI endpoint? Show multiple Pydantic models and embedded Body() values." },
      { fr: "Modèles imbriqués", obj: "Models qui contiennent des models",
        en: "How do I use nested Pydantic models in FastAPI? Show models with submodels, lists of submodels, and arbitrarily nested data." },
      { fr: "Gestion des erreurs", obj: "HTTPException + handlers",
        en: "How do I handle errors in FastAPI? Show raising HTTPException, custom exception handlers, and overriding default exception handlers." },
      { fr: "Encodeurs / json compatibles", obj: "jsonable_encoder",
        en: "What is jsonable_encoder in FastAPI? Show converting Pydantic models to JSON-compatible dicts and use cases for PATCH operations." },
      { fr: "Encodage et mise à jour partielle", obj: "PATCH avec exclude_unset",
        en: "How do I implement PATCH (partial update) endpoints in FastAPI? Show using exclude_unset, model_copy, and update patterns." },
    ],
  },
  {
    num: "FA3",
    title: "FastAPI · Dépendances & sécurité",
    goal: "Injection de dépendances, authentification, autorisations.",
    icon: "vpn_key",
    corpus: "fastapi",
    concepts: [
      { fr: "Dependency Injection (intro)", obj: "Depends() pour partager du code",
        en: "How does dependency injection work in FastAPI with Depends()? Show simple dependencies, sharing code between path operations, and dependency resolution." },
      { fr: "Sous-dépendances", obj: "Dépendances qui en dépendent",
        en: "How do sub-dependencies work in FastAPI? Show nested dependencies, dependency caching, and the use_cache parameter." },
      { fr: "Classes comme dépendances", obj: "Class-based dependencies",
        en: "How do I use classes as dependencies in FastAPI? Show callable classes, instance attributes as configuration, and benefits over function deps." },
      { fr: "Dépendances dans le décorateur", obj: "dependencies= sans param",
        en: "How do path operation decorator dependencies work in FastAPI? Show using dependencies= argument for side-effect-only dependencies." },
      { fr: "yield dependencies", obj: "Setup/teardown avec yield",
        en: "How do dependencies with yield work in FastAPI? Show setup and teardown logic, database session pattern, and exception handling in yield deps." },
      { fr: "Sécurité — OAuth2 Password", obj: "OAuth2PasswordBearer + form login",
        en: "How do I implement OAuth2 password authentication in FastAPI? Show OAuth2PasswordBearer, OAuth2PasswordRequestForm, and the /token endpoint." },
      { fr: "JWT (JSON Web Tokens)", obj: "Encoder, décoder, expirer",
        en: "How do I implement JWT authentication in FastAPI? Show encoding tokens with jose, decoding, expiration claims, and protecting endpoints." },
      { fr: "Scopes et permissions", obj: "Granularité d'accès",
        en: "How do OAuth2 scopes work in FastAPI? Show declaring scopes, requiring them per endpoint, and Security() vs Depends()." },
    ],
  },
  {
    num: "FA4",
    title: "FastAPI · Avancé & production",
    goal: "Middleware, async, déploiement, tests.",
    icon: "rocket_launch",
    corpus: "fastapi",
    concepts: [
      { fr: "Middleware", obj: "Intercepter requêtes et réponses",
        en: "How does middleware work in FastAPI? Show writing custom middleware with @app.middleware, modifying requests and responses, and ordering." },
      { fr: "CORS", obj: "CORSMiddleware pour le front",
        en: "How do I configure CORS in FastAPI? Show CORSMiddleware, allow_origins, allow_credentials, allow_methods, and allow_headers." },
      { fr: "Background tasks", obj: "BackgroundTasks après la réponse",
        en: "How do background tasks work in FastAPI? Show BackgroundTasks parameter, when to use them vs Celery, and limitations." },
      { fr: "Lifespan events", obj: "Startup/shutdown propre",
        en: "How do lifespan events work in FastAPI? Show the lifespan context manager, replacing on_event handlers, and resource management." },
      { fr: "Streaming et SSE", obj: "StreamingResponse pour chat live",
        en: "How do I stream responses in FastAPI? Show StreamingResponse, Server-Sent Events (text/event-stream), and async generators." },
      { fr: "WebSockets", obj: "Connexion bidirectionnelle",
        en: "How do WebSockets work in FastAPI? Show @app.websocket route, accept/send/receive, and managing connection lifecycle." },
      { fr: "Tests avec TestClient", obj: "Tester sans vrai serveur",
        en: "How do I test a FastAPI app? Show TestClient from fastapi.testclient, testing endpoints, overriding dependencies, and async tests." },
      { fr: "Déploiement", obj: "uvicorn, gunicorn, Docker",
        en: "How do I deploy a FastAPI app to production? Show uvicorn with workers, gunicorn with uvicorn workers, Dockerfile, and reverse proxy setup." },
    ],
  },

  // ==========================================================================
  // Pydantic — validation, sérialisation, settings
  // ==========================================================================
  {
    num: "PD1",
    title: "Pydantic · Modèles",
    goal: "Définir des modèles de données validés et typés.",
    icon: "schema",
    corpus: "pydantic",
    concepts: [
      { fr: "Première classe BaseModel", obj: "Champs typés validés",
        en: "How do I create my first Pydantic v2 BaseModel? Show field declarations, automatic validation, and instantiation from dict and kwargs." },
      { fr: "Types de champs", obj: "int, str, list, dict, Optional...",
        en: "What field types does Pydantic v2 support? Show str, int, float, bool, list, dict, datetime, UUID, EmailStr, and Optional/None." },
      { fr: "Valeurs par défaut", obj: "Field() et default_factory",
        en: "How do default values work in Pydantic v2? Show Field(default=...), default_factory for mutable defaults, and required vs optional fields." },
      { fr: "Contraintes via Field()", obj: "min_length, ge, le, pattern",
        en: "How do I add constraints to Pydantic v2 fields with Field()? Show min_length, max_length, ge, le, gt, lt, pattern, and alias." },
      { fr: "Modèles imbriqués", obj: "Composition + validation récursive",
        en: "How do nested models work in Pydantic v2? Show models with submodels, lists of submodels, and dict-to-model conversion." },
      { fr: "Types alternatifs Union", obj: "X | Y et discriminated unions",
        en: "How do union types work in Pydantic v2? Show X | Y syntax, discriminated unions with Field(discriminator=...), and validation behavior." },
      { fr: "Aliases et populate_by_name", obj: "Champs aux noms multiples",
        en: "How do field aliases work in Pydantic v2? Show alias, validation_alias, serialization_alias, AliasChoices, and populate_by_name." },
      { fr: "ConfigDict", obj: "model_config par modèle",
        en: "How does model_config work in Pydantic v2? Show ConfigDict options like frozen, extra, str_strip_whitespace, populate_by_name, and json_schema_extra." },
    ],
  },
  {
    num: "PD2",
    title: "Pydantic · Validation & sérialisation",
    goal: "Personnaliser la validation et la sortie JSON.",
    icon: "compare_arrows",
    corpus: "pydantic",
    concepts: [
      { fr: "Validators personnalisés", obj: "@field_validator + @model_validator",
        en: "How do custom validators work in Pydantic v2? Show @field_validator and @model_validator decorators, modes (before, after, wrap), and reuse." },
      { fr: "model_dump et model_dump_json", obj: "Sérialisation contrôlée",
        en: "How do model_dump and model_dump_json work in Pydantic v2? Show include, exclude, exclude_unset, exclude_defaults, by_alias, and round-trip." },
      { fr: "Serializers personnalisés", obj: "@field_serializer + @model_serializer",
        en: "How do custom serializers work in Pydantic v2? Show @field_serializer and @model_serializer decorators with field-level and model-level examples." },
      { fr: "TypeAdapter (ex parse_obj_as)", obj: "Valider sans BaseModel",
        en: "What is TypeAdapter in Pydantic v2? Show validating arbitrary types like list[int] or dict[str, MyModel] without creating a BaseModel." },
      { fr: "Computed fields", obj: "@computed_field pour propriétés calculées",
        en: "How do computed fields work in Pydantic v2? Show @computed_field decorator, when they're computed, and including them in serialization." },
      { fr: "Pydantic Settings (env vars)", obj: "BaseSettings depuis .env",
        en: "How does pydantic-settings work? Show BaseSettings, env_prefix, env_file, SettingsConfigDict, and SecretStr for sensitive values." },
      { fr: "JSON Schema generation", obj: "model_json_schema() pour OpenAPI",
        en: "How does JSON Schema generation work in Pydantic v2? Show model_json_schema(), json_schema_extra, and customizing schema output." },
      { fr: "Migration v1 → v2", obj: "Changements clés",
        en: "What are the main breaking changes when migrating Pydantic v1 to v2? Show renamed methods, ConfigDict vs class Config, and validator decorators." },
    ],
  },

  // ==========================================================================
  // Next.js — App Router moderne (v16)
  // ==========================================================================
  {
    num: "NX1",
    title: "Next.js · App Router",
    goal: "Routes, layouts, navigation, fichiers spéciaux.",
    icon: "route",
    corpus: "nextjs",
    concepts: [
      { fr: "Structure d'un projet App Router", obj: "app/, page.tsx, layout.tsx",
        en: "How is a Next.js App Router project structured? Show app/ directory, page.tsx, layout.tsx, special files, and route segments." },
      { fr: "Routes et pages", obj: "page.tsx par segment",
        en: "How do pages work in Next.js App Router? Show creating routes with page.tsx files, route segments, and accessing route information." },
      { fr: "Layouts partagés", obj: "layout.tsx persistant entre routes",
        en: "How do layouts work in Next.js App Router? Show layout.tsx, nested layouts, root layout requirements, and templates vs layouts." },
      { fr: "Routes dynamiques", obj: "[slug] et catch-all",
        en: "How do dynamic routes work in Next.js App Router? Show [slug], [...slug] catch-all, [[...slug]] optional catch-all, and accessing params." },
      { fr: "Linking et navigation", obj: "<Link> et useRouter",
        en: "How does navigation work in Next.js App Router? Show next/link, programmatic navigation with useRouter, prefetching, and scroll behavior." },
      { fr: "Loading et error states", obj: "loading.tsx, error.tsx",
        en: "How do loading.tsx and error.tsx work in Next.js App Router? Show suspense boundaries, error boundaries, and not-found.tsx." },
      { fr: "Route groups et privates", obj: "(group) et _private",
        en: "How do route groups and private folders work in Next.js App Router? Show (groupname) parentheses syntax and _private underscore folders." },
      { fr: "Métadonnées et SEO", obj: "metadata export, generateMetadata",
        en: "How does metadata work in Next.js App Router? Show static metadata export, generateMetadata for dynamic metadata, and Open Graph fields." },
    ],
  },
  {
    num: "NX2",
    title: "Next.js · Composants & rendu",
    goal: "Server Components, Client Components, streaming.",
    icon: "layers",
    corpus: "nextjs",
    concepts: [
      { fr: "Server Components (par défaut)", obj: "Rendu côté serveur, zéro JS au client",
        en: "What are Server Components in Next.js App Router? Show how they work by default, when to use them, and what they can and cannot do." },
      { fr: "Client Components", obj: "'use client' pour interactivité",
        en: "What are Client Components in Next.js App Router? Show the 'use client' directive, when to use them, and how to compose them with Server Components." },
      { fr: "Passage server → client", obj: "Props serializables uniquement",
        en: "How do I pass data from a Server Component to a Client Component in Next.js App Router? Show serializable props and component composition patterns." },
      { fr: "Suspense et streaming", obj: "<Suspense> pour rendu progressif",
        en: "How does streaming work in Next.js App Router with Suspense? Show wrapping async components, fallbacks, and progressive enhancement." },
      { fr: "Server Actions", obj: "Mutations sans API route",
        en: "What are Server Actions in Next.js App Router? Show 'use server', invoking from forms and Client Components, and useActionState." },
      { fr: "Forms et useActionState", obj: "Soumissions progressives",
        en: "How do forms with Server Actions work in Next.js? Show <form action={...}>, useActionState for state/feedback, and progressive enhancement." },
      { fr: "Parallel et intercepted routes", obj: "@slot et (.)route",
        en: "How do parallel routes and intercepted routes work in Next.js App Router? Show @slot named slots, default.tsx, and (.) intercepting routes for modals." },
      { fr: "Optimisation des images", obj: "<Image> de next/image",
        en: "How does next/image work in Next.js? Show the Image component, sizing, priority, placeholder, formats, and remote images configuration." },
    ],
  },
  {
    num: "NX3",
    title: "Next.js · Données & cache",
    goal: "fetch, cache, revalidation.",
    icon: "cached",
    corpus: "nextjs",
    concepts: [
      { fr: "Data fetching", obj: "fetch() dans Server Component",
        en: "How do I fetch data in Next.js App Router Server Components? Show using fetch directly, async components, and parallel data fetching." },
      { fr: "Caching de fetch", obj: "Caching automatique + revalidate",
        en: "How does fetch caching work in Next.js App Router? Show the default cache behavior, no-store, force-cache, and revalidate option in fetch." },
      { fr: "revalidateTag et revalidatePath", obj: "Invalider à la demande",
        en: "How do revalidateTag and revalidatePath work in Next.js? Show on-demand revalidation from Server Actions, tagging fetch calls, and cacheLife." },
      { fr: "Cache Components (PPR)", obj: "cacheComponents flag",
        en: "What is the cacheComponents flag in Next.js 16 (replacing experimental PPR)? Show the configuration, behavior, and migration patterns." },
      { fr: "Route Handlers (API routes)", obj: "route.ts pour endpoints",
        en: "How do Route Handlers work in Next.js App Router? Show route.ts files, GET/POST/etc handlers, Request/Response, and NextRequest helpers." },
      { fr: "Cookies et headers async", obj: "await cookies() et await headers()",
        en: "How do cookies() and headers() work in Next.js 16 App Router? Show that they are now async (await) and how to read and set cookies." },
      { fr: "Middleware / proxy", obj: "proxy.ts (anciennement middleware)",
        en: "How does proxy.ts work in Next.js 16 (formerly middleware.ts)? Show request matching, redirects, rewrites, and the runtime constraints." },
      { fr: "Variables d'environnement", obj: "NEXT_PUBLIC_* côté client",
        en: "How do environment variables work in Next.js? Show .env files, NEXT_PUBLIC_ prefix for client-side, and accessing process.env at build vs runtime." },
    ],
  },

  // ==========================================================================
  // TypeScript — typage moderne pour le frontend (et plus)
  // ==========================================================================
  {
    num: "TS1",
    title: "TypeScript · Types essentiels",
    goal: "Couvrir la majorité du code quotidien.",
    icon: "abc",
    corpus: "typescript",
    concepts: [
      { fr: "Types primitifs", obj: "string, number, boolean, null, undefined",
        en: "What are the primitive types in TypeScript? Show string, number, boolean, null, undefined, bigint, symbol, and the difference between any, unknown, and never." },
      { fr: "Arrays et tuples", obj: "T[] vs [T, T]",
        en: "How do arrays and tuples work in TypeScript? Show T[], Array<T>, readonly arrays, and labeled tuples like [string, number]." },
      { fr: "Object types", obj: "Forme d'un objet",
        en: "How do object types work in TypeScript? Show inline object types, optional properties (?), readonly modifier, and excess property checks." },
      { fr: "Interfaces vs Types", obj: "Quand utiliser lequel ?",
        en: "What is the difference between interface and type in TypeScript? Show when to use each, declaration merging, and extends vs intersection." },
      { fr: "Union et intersection", obj: "A | B et A & B",
        en: "How do union and intersection types work in TypeScript? Show union types (A | B), intersection types (A & B), and narrowing with type guards." },
      { fr: "Literal types", obj: "'foo' | 'bar' comme types",
        en: "What are literal types in TypeScript? Show string literals, numeric literals, boolean literals, and using them with unions to make string enums." },
      { fr: "Functions et signatures", obj: "Params, retours, overloads",
        en: "How do function types work in TypeScript? Show parameter types, return types, optional parameters, default parameters, rest parameters, and function overloads." },
      { fr: "Type narrowing", obj: "typeof, instanceof, in, custom guards",
        en: "How does type narrowing work in TypeScript? Show typeof, instanceof, in operator, equality narrowing, and user-defined type predicates (x is T)." },
    ],
  },
  {
    num: "TS2",
    title: "TypeScript · Génériques & utilitaires",
    goal: "Écrire du code réutilisable et typé.",
    icon: "code",
    corpus: "typescript",
    concepts: [
      { fr: "Génériques basiques", obj: "<T> sur fonctions et types",
        en: "How do generics work in TypeScript? Show generic functions, generic interfaces, generic classes, and type parameter inference." },
      { fr: "Contraintes sur génériques", obj: "T extends Constraint",
        en: "How do generic constraints work in TypeScript? Show T extends ..., constrained type parameters, and using constraints to access properties." },
      { fr: "Types conditionnels", obj: "T extends U ? X : Y",
        en: "How do conditional types work in TypeScript? Show T extends U ? X : Y, infer keyword, distributive conditional types, and practical examples." },
      { fr: "Mapped types", obj: "{ [K in keyof T]: ... }",
        en: "How do mapped types work in TypeScript? Show iterating over keys with keyof, modifiers (readonly, ?), and as remapping clauses." },
      { fr: "Utility types", obj: "Partial, Required, Pick, Omit, Record",
        en: "What are the most useful TypeScript utility types? Show Partial, Required, Readonly, Pick, Omit, Record, ReturnType, Parameters, Awaited with examples." },
      { fr: "keyof et typeof", obj: "Dériver des types de valeurs",
        en: "How do keyof and typeof operators work in TypeScript? Show extracting keys, getting the type of a value, and combining them for typed object access." },
      { fr: "Template literal types", obj: "`${A}_${B}` au type level",
        en: "How do template literal types work in TypeScript? Show string interpolation in types, combined with unions, and creating typed event names or CSS properties." },
      { fr: "Index signatures", obj: "[key: string]: T",
        en: "How do index signatures work in TypeScript? Show string and number index signatures, when to use them vs Record, and Record vs Map." },
    ],
  },
  {
    num: "TS3",
    title: "TypeScript · Avancé",
    goal: "Patterns puissants pour des APIs typées.",
    icon: "psychology",
    corpus: "typescript",
    concepts: [
      { fr: "Discriminated unions", obj: "Tag commun pour pattern matching",
        en: "How do discriminated unions work in TypeScript? Show tagged unions with a common literal property, switch-based narrowing, and exhaustive checks with never." },
      { fr: "Exhaustiveness checking", obj: "Garantie de couvrir tous les cas",
        en: "How does exhaustiveness checking work in TypeScript? Show the never type, default case with assertNever, and ensuring switch statements cover all union members." },
      { fr: "satisfies operator", obj: "Vérifier sans élargir",
        en: "How does the satisfies operator work in TypeScript? Show enforcing a type without widening, contrasted with type annotations, and practical use cases." },
      { fr: "const assertions", obj: "as const pour des literals",
        en: "How do const assertions (as const) work in TypeScript? Show preserving literal types, making arrays readonly tuples, and use cases for enums and config." },
      { fr: "Branded types", obj: "Distinguer string et UserId",
        en: "How do branded types (nominal typing) work in TypeScript? Show using intersection with unique symbol, creating type-safe IDs, and use cases for primitives." },
      { fr: "Modules et namespaces", obj: "import/export, déclaration",
        en: "How do modules and namespaces work in TypeScript? Show ES module syntax, import type, re-exports, default exports, and when (rarely) to use namespaces." },
      { fr: "Decorators (stage 3)", obj: "TC39 decorators modernes",
        en: "How do TC39 (stage 3) decorators work in TypeScript? Show class decorators, method decorators, accessor decorators, and the new ClassMethodDecoratorContext." },
      { fr: "Declaration files (.d.ts)", obj: "Typer du JS existant",
        en: "How do declaration files (.d.ts) work in TypeScript? Show ambient declarations, declaring modules, declare global, and authoring types for untyped npm packages." },
    ],
  },

  // ==========================================================================
  // Tailwind CSS — utilitaires et personnalisation
  // ==========================================================================
  {
    num: "TW1",
    title: "Tailwind · Utilities & responsive",
    goal: "Maîtriser les classes utilitaires pour styler vite.",
    icon: "format_paint",
    corpus: "tailwind",
    concepts: [
      { fr: "Philosophie utility-first", obj: "Une classe = une propriété",
        en: "What is the utility-first philosophy of Tailwind CSS? Explain the approach, its advantages over traditional CSS, and how to compose utilities." },
      { fr: "Spacing (padding, margin, gap)", obj: "p-*, m-*, gap-*",
        en: "How does spacing work in Tailwind CSS? Show padding (p, px, py), margin (m, mx, my), gap, space-x, space-y, and the spacing scale." },
      { fr: "Sizing (width, height, min/max)", obj: "w-*, h-*, max-w-*",
        en: "How does sizing work in Tailwind CSS? Show width, height, min-w, max-w, min-h, max-h, fixed sizes, fractions, percentages, and viewport units." },
      { fr: "Flexbox", obj: "flex, items-*, justify-*",
        en: "How does Flexbox work in Tailwind CSS? Show flex, flex-direction, flex-wrap, align-items, justify-content, gap, and common patterns." },
      { fr: "Grid", obj: "grid, grid-cols-*, gap-*",
        en: "How does Grid work in Tailwind CSS? Show grid, grid-template-columns, grid-template-rows, gap, col-span, row-span, and auto-fit patterns." },
      { fr: "Typography", obj: "text-*, font-*, leading-*",
        en: "How do typography utilities work in Tailwind CSS? Show font size (text-*), font weight, line height (leading), letter spacing, text alignment, and color." },
      { fr: "Couleurs et palette", obj: "bg-*, text-*, border-*",
        en: "How do colors work in Tailwind CSS? Show the default palette, opacity modifiers (bg-blue-500/50), arbitrary values [#fff], and the color naming scheme." },
      { fr: "Responsive design", obj: "sm:, md:, lg:, xl:",
        en: "How does responsive design work in Tailwind CSS? Show breakpoint prefixes (sm:, md:, lg:, xl:, 2xl:), mobile-first approach, and arbitrary breakpoints." },
    ],
  },
  {
    num: "TW2",
    title: "Tailwind · Personnalisation",
    goal: "Adapter Tailwind à ton design system.",
    icon: "tune",
    corpus: "tailwind",
    concepts: [
      { fr: "Configuration v4 avec @theme", obj: "Tokens via CSS",
        en: "How does Tailwind CSS v4 configuration work? Show the @theme directive in CSS, defining custom colors, spacing, fonts, and how it replaces tailwind.config.js." },
      { fr: "Variants (hover, focus, dark)", obj: "Pseudo-classes en utilitaires",
        en: "How do variants work in Tailwind CSS? Show hover:, focus:, active:, disabled:, dark:, group-hover:, peer-checked:, and chaining variants." },
      { fr: "Arbitrary values", obj: "p-[13px] et bg-[#1a2b3c]",
        en: "How do arbitrary values work in Tailwind CSS? Show square bracket syntax for one-off values like w-[42rem], bg-[#1a2b3c], grid-cols-[200px_1fr], and when to use them." },
      { fr: "@apply et components", obj: "Réutiliser des classes",
        en: "When and how should I use @apply in Tailwind CSS? Show creating component classes, the tradeoffs vs utility-first, and the recommended patterns." },
      { fr: "Dark mode", obj: "Stratégies media vs class",
        en: "How does dark mode work in Tailwind CSS? Show the media strategy vs class strategy, toggling via JS, and writing dark mode styles with the dark: variant." },
      { fr: "Plugins", obj: "Étendre Tailwind",
        en: "How do plugins work in Tailwind CSS? Show installing official plugins (@tailwindcss/forms, typography), writing custom plugins, and using addUtilities and addComponents." },
      { fr: "Animations et transitions", obj: "transition, animate-*, keyframes",
        en: "How do animations and transitions work in Tailwind CSS? Show transition utilities, duration, easing, animate-spin/pulse/bounce, and custom keyframes." },
      { fr: "Container queries (v4)", obj: "@container et @sm:, @md:",
        en: "How do container queries work in Tailwind CSS v4? Show @container, @sm:, @md: variants based on container size rather than viewport, and use cases." },
    ],
  },

  // ═══════════════════════════════════════════════════ HTML (MDN)
  {
    num: "HT1",
    title: "HTML · Structure & sémantique",
    goal: "Écrire un HTML moderne, accessible et bien structuré.",
    icon: "html",
    corpus: "html",
    concepts: [
      { fr: "Squelette HTML5", obj: "<!DOCTYPE>, <html lang>, <meta charset>",
        en: "What is the minimal HTML5 document skeleton? Show DOCTYPE, html lang, head with charset and viewport meta tags, and the role of each." },
      { fr: "Balises sémantiques", obj: "header, main, article, section, aside, footer, nav",
        en: "What are the semantic HTML5 sectioning elements? Explain header, nav, main, article, section, aside, footer with examples of proper nesting for a blog page." },
      { fr: "Titres h1-h6 et structure", obj: "Hiérarchie + lecture par les screen readers",
        en: "How should heading levels h1 through h6 be used in HTML for accessibility? Show document outline, screen reader behavior, and common mistakes." },
      { fr: "Liens et navigation", obj: "<a href>, target, rel, ancres internes",
        en: "How do anchor tags work in HTML? Show href types (absolute, relative, fragment, mailto, tel), target=_blank with rel=noopener, and internal anchor navigation." },
      { fr: "Listes ul / ol / dl", obj: "Listes ordonnées, non-ordonnées, de définitions",
        en: "What are the three list types in HTML (ul, ol, dl)? Show start, reversed, type attributes for ol, and the dt/dd pairs in definition lists." },
      { fr: "Images et alt", obj: "<img>, srcset, sizes, picture, alt text",
        en: "How do images work in HTML? Show img with alt attribute for accessibility, srcset for retina, the picture element for art direction, and lazy loading." },
      { fr: "Tableaux accessibles", obj: "thead, tbody, caption, scope sur th",
        en: "How do I write an accessible HTML table? Show table, thead, tbody, tfoot, caption, th with scope attribute, and complex tables with headers attribute." },
      { fr: "Formulaires de base", obj: "<form>, <input>, types, labels",
        en: "How do HTML forms work? Show form action and method, all input types (text, email, password, number, date, etc.), labels with for attribute, and form submission." },
      { fr: "Validation HTML5", obj: "required, pattern, min/max, type=email",
        en: "How does HTML5 form validation work without JavaScript? Show required, pattern (regex), min/max, type validation (email, url, number), and the :invalid pseudo-class." },
      { fr: "Audio, vidéo, iframe", obj: "Médias embarqués et sécurité",
        en: "How do audio, video, and iframe elements work in HTML? Show controls, sources for fallback formats, iframe sandbox attribute for security." },
      { fr: "ARIA et accessibilité", obj: "role, aria-label, aria-hidden",
        en: "What is ARIA in HTML and when do I need it? Show the first rule of ARIA, role attribute, aria-label, aria-hidden, aria-live regions, and landmark roles." },
      { fr: "Métadonnées et SEO", obj: "<meta description>, Open Graph, robots",
        en: "What HTML meta tags matter for SEO and social sharing? Show meta description, Open Graph (og:title, og:image), Twitter cards, robots and canonical." },
    ],
  },

  // ═══════════════════════════════════════════════════ CSS (MDN)
  {
    num: "CS1",
    title: "CSS · Sélecteurs, box model & layout",
    goal: "Maîtriser les fondamentaux du CSS et les systèmes de mise en page.",
    icon: "css",
    corpus: "css",
    concepts: [
      { fr: "Sélecteurs essentiels", obj: "Class, id, descendance, attribut",
        en: "What are the main CSS selectors? Show element, class, id, descendant, child (>), adjacent (+), sibling (~), attribute selectors, and how to combine them." },
      { fr: "Spécificité et cascade", obj: "Comment CSS résout les conflits",
        en: "How does CSS specificity work? Show the calculation (inline, id, class, element), the cascade order, !important, and how to debug specificity issues." },
      { fr: "Pseudo-classes et éléments", obj: ":hover, :focus, ::before",
        en: "What are CSS pseudo-classes and pseudo-elements? Show :hover, :focus, :nth-child, :not, ::before, ::after, ::placeholder with examples." },
      { fr: "Box model", obj: "content, padding, border, margin",
        en: "How does the CSS box model work? Show content, padding, border, margin, and the difference between box-sizing content-box and border-box." },
      { fr: "Display et positionnement", obj: "block, inline, flex, grid + position",
        en: "How do display and position properties work in CSS? Show block vs inline vs inline-block, position static/relative/absolute/fixed/sticky with examples." },
      { fr: "Flexbox", obj: "display:flex, justify-content, align-items, gap",
        en: "How does Flexbox work in CSS? Show display:flex, flex-direction, justify-content, align-items, gap, flex-grow/shrink/basis with a centered card example." },
      { fr: "Grid", obj: "grid-template-columns, gap, areas",
        en: "How does CSS Grid work? Show display:grid, grid-template-columns/rows (fr units, repeat, minmax, auto-fit), gap, and grid-template-areas for layouts." },
      { fr: "Unités CSS", obj: "px, em, rem, %, vh/vw, ch",
        en: "What are the different CSS units? Show absolute (px) vs relative (em, rem, %, vh, vw, ch, fr), when to use each, and common pitfalls." },
      { fr: "Couleurs modernes", obj: "rgb, hsl, oklch, color-mix",
        en: "What are the modern CSS color formats? Show rgb/rgba, hsl/hsla, hex, oklch, color-mix(), and the new color-contrast function." },
      { fr: "Custom properties (vars)", obj: "--my-var et calc()",
        en: "How do CSS custom properties (variables) work? Show declaring --vars, using var() with fallback, calc() with variables, and theming with @media." },
      { fr: "Responsive & media queries", obj: "@media et mobile-first",
        en: "How do CSS media queries work for responsive design? Show min-width vs max-width, mobile-first approach, prefers-color-scheme, prefers-reduced-motion." },
      { fr: "Transitions & animations", obj: "transition, @keyframes, animation",
        en: "How do CSS transitions and animations work? Show the transition shorthand, easing functions, @keyframes, animation properties, and prefers-reduced-motion accessibility." },
    ],
  },

  // ═══════════════════════════════════════════════════ JavaScript (MDN)
  {
    num: "JS1",
    title: "JavaScript · Syntaxe moderne",
    goal: "Coder en JavaScript ES2024 — types, fonctions, async, DOM.",
    icon: "javascript",
    corpus: "javascript",
    concepts: [
      { fr: "let, const, var", obj: "Portée et hoisting des déclarations",
        en: "What is the difference between let, const, and var in JavaScript? Show scope (block vs function), hoisting, the temporal dead zone, and when to use each." },
      { fr: "Types primitifs", obj: "string, number, boolean, null, undefined, bigint, symbol",
        en: "What are the 7 primitive types in JavaScript? Show typeof for each (string, number, boolean, null, undefined, bigint, symbol), the typeof null quirk, and coercion rules." },
      { fr: "Tableaux et méthodes", obj: "map, filter, reduce, find, some, every",
        en: "What are the most useful Array methods in JavaScript? Show map, filter, reduce, find, some, every, flatMap with practical examples and chaining." },
      { fr: "Objets et destructuring", obj: "{ a, b } = obj, spread, rest",
        en: "How does object destructuring and spread work in JavaScript? Show destructuring with rename and default values, nested destructuring, and the spread/rest operators." },
      { fr: "Functions et arrow", obj: "function vs () => et 'this'",
        en: "How are arrow functions different from regular functions in JavaScript? Show this binding, arguments, hoisting, and when to use each (event handlers, methods, callbacks)." },
      { fr: "Promises et async/await", obj: "then, catch, finally, await",
        en: "How do Promises and async/await work in JavaScript? Show Promise.all, Promise.race, error handling with try/catch in async functions, and common pitfalls." },
      { fr: "Modules ES (import/export)", obj: "named, default, dynamic import()",
        en: "How do ES modules work in JavaScript? Show export named vs default, import syntax, side-effect imports, dynamic import() with code splitting." },
      { fr: "Classes et héritage", obj: "class, extends, super, #private",
        en: "How do JavaScript classes work? Show class syntax, constructor, methods, static, extends/super, getter/setter, and the new # private fields syntax." },
      { fr: "Closures", obj: "Une fonction qui se souvient",
        en: "What is a closure in JavaScript? Explain lexical scope, show a counter factory, use cases (module pattern, currying), and how closures cause memory leaks." },
      { fr: "DOM : sélection et événements", obj: "querySelector, addEventListener",
        en: "How do I manipulate the DOM in JavaScript? Show querySelector, querySelectorAll, addEventListener, event delegation, preventDefault, and event.target vs currentTarget." },
      { fr: "Fetch et JSON", obj: "fetch(), Response, async/await, erreurs",
        en: "How does the Fetch API work in JavaScript? Show fetch with options (method, headers, body), parsing JSON, handling errors, and using AbortController for cancellation." },
      { fr: "Optional chaining & nullish", obj: "?., ??, ??=",
        en: "What are the optional chaining (?.) and nullish coalescing (??) operators in JavaScript? Show usage with nested objects, function calls, and the difference with ||." },
    ],
  },
];

/** Total des concepts pour affichage du compteur dans la sidebar */
export const TOTAL_CONCEPTS = CURRICULUM.reduce(
  (sum, lvl) => sum + lvl.concepts.length,
  0,
);
